import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react';
import { Card, CardTitle, CardSubtitle, Row, Table, Button, Alert, Pagination, PaginationItem, PaginationLink, Progress, Col } from 'reactstrap';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Row>
            <Card body className={styles.card50}>
              <CardTitle tag="h5">What is 2 + 2?</CardTitle>
              <CardSubtitle tag="h6" className="mb-2 text-muted">Choose one:  "A"</CardSubtitle>
              <Table hover>
                <thead>
                  <tr>
                    <th className={styles.col10}>#</th>
                    <th>Description</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">A</th>
                    <td>1</td>
                  </tr>
                  <tr>
                    <th scope="row">B</th>
                    <td>4</td>
                  </tr>
                  <tr>
                    <th scope="row">C</th>
                    <td>2</td>
                  </tr>
                  <tr>
                    <th scope="row">D</th>
                    <td>3</td>
                  </tr>
                </tbody>
              </Table>

              {/*  Display Correct Answer */}
              <Alert color="danger">
                The Correct Answer is "B"
              </Alert>

              {/* Submit/ */}
              <Button color="primary">Submit</Button>{' '}

              {/* Card Navigation */}
              <Row>
                <Col className={styles.rowTop5}>
                <Pagination size="lg" aria-label="Page navigation example">
                  <PaginationItem>
                    <PaginationLink first href="#" />
                  </PaginationItem>
                  <PaginationItem>
                    <PaginationLink previous href="#" />
                  </PaginationItem>
                  <PaginationItem>
                    <PaginationLink href="#">
                      1
                    </PaginationLink>
                  </PaginationItem>
                  <PaginationItem>
                    <PaginationLink href="#">
                      2
                    </PaginationLink>
                  </PaginationItem>
                  <PaginationItem>
                    <PaginationLink href="#">
                      3
                    </PaginationLink>
                  </PaginationItem>
                  <PaginationItem>
                    <PaginationLink next href="#" />
                  </PaginationItem>
                  <PaginationItem>
                    <PaginationLink last href="#" />
                  </PaginationItem>
                </Pagination>
                </Col>
              </Row>

              {/* Progress Section */}
              <Row>
                <Col className={styles.rowTop5}>
                  <Progress multi>
                    <Progress striped bar color="success" value="50" />
                    <Progress striped bar color="danger" value="20" />
                  </Progress>
                </Col>
              </Row>

            </Card>
        </Row>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
