import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react';
import { Card, CardTitle, CardSubtitle, Row, Table } from 'reactstrap';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Row>
            <Card body className={styles.card50}>
              <CardTitle tag="h5">Whats 2 + 2?</CardTitle>
              <CardSubtitle tag="h6" className="mb-2 text-muted">Choose one</CardSubtitle>
              <Table hover>
                <thead>
                  <tr>
                    <th className={styles.col10}>#</th>
                    <th>Description</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">A</th>
                    <td>1</td>
                  </tr>
                  <tr>
                    <th scope="row">B</th>
                    <td>4</td>
                  </tr>
                  <tr>
                    <th scope="row">C</th>
                    <td>2</td>
                  </tr>
                  <tr>
                    <th scope="row">D</th>
                    <td>3</td>
                  </tr>
                </tbody>
              </Table>
            </Card>
        </Row>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
